config/routes.rb
Rails.application.routes.draw do
  get '/healthcheck' => 'healthcheck#check'

  resources :notes do
    put 'resolve', on: :member
  end

  get 'downtimes' => 'downtimes#index'

  resources :artefacts, only: [:new, :create, :update]

  resources :editions do
    member do
      get 'diff'
      get 'metadata'
      get 'history'
      get 'admin'
      get 'tagging', to: "editions#linking"
      get 'related_external_links', to: "editions#linking"
      get 'unpublish'
      post 'duplicate'
      post 'update_tagging'
      post 'process_unpublish'
      patch 'update_related_external_links'
      post 'progress'
      put 'review'
      post 'skip_fact_check', to: 'editions#progress',
        edition: {
          activity: {
            request_type: 'skip_fact_check',
            comment: "Fact check skipped by request."
            }
          }
    end

    resource :downtime, only: [:new, :create, :edit, :update, :destroy]
  end

  get 'reports' => 'reports#index', as: :reports
  get 'reports/progress' => 'reports#progress', as: :progress_report
  get 'reports/organisation-content' => 'reports#organisation_content', :as => :organisation_content_report
  get 'reports/edition-churn' => 'reports#edition_churn', as: "edition_churn_report"
  get 'reports/content_workflow' => 'reports#content_workflow', as: "content_workflow_report"

  get 'user_search' => 'user_search#index'

  resources :link_check_reports, only: %i(create show)

  post "/link-checker-api-callback" => "link_checker_api#callback", as: "link_checker_api_callback"
  get 'api/lookup-by-base-path', to: "publishing_api_proxy#lookup_by_base_path"

  resources :publications
  root to: 'root#index'

  # We used to nest all URLs under /admin so we now redirect that
  # in case people had bookmarks set up. Using a proc as otherwise the
  # path parameter gets escaped
  get "/admin(/*path)", to: redirect { |params, _req| "/#{params[:path]}" }

  mount GovukAdminTemplate::Engine, at: "/style-guide"
end

app/views/shared/_admin.html.erb
<% if @resource.can_destroy? %>
  <h3 class="remove-top-margin add-bottom-margin">Delete edition</h3>
  <%= button_to "Delete this edition – ##{@resource.version_number}", path_for_edition(@resource), :method => :delete, :class => "btn btn-danger" %>
<% end %>

<% if @resource.can_destroy? && @resource.fact_check? %><hr/><% end %>

<% if @resource.fact_check? %>
  <h3 class="add-bottom-margin">Skip fact check</h3>
  <%= button_to "Skip fact check", skip_fact_check_for_edition(@resource), :method => :post, :class => "btn btn-default" %>
<% end %>

<% if @edition.published? && @edition.can_create_new_edition? %>
  <h3 class="remove-top-margin">Change format of edition</h3>

<%= render partial: "shared/clone_buttons",
    locals: {
      edition: @edition,
      edition_class: @edition.class,
    }
%>

<% end %>

app/views/shared/_clone_buttons.html.erb
<% if edition.can_create_new_edition? && (edition.class == edition_class) %>
  <div>
    <p>No content will be lost, but content in some fields might not make it into the new edition. If it can't be copied to a new format it will still be available in the previous edition. Content in multiple fields might be combined into a single field.</p>
  <% if @edition.respond_to?(:parts) %>
    <p>All parts of Guide Editions will be copied across. If the format you are converting to doesn't have parts, the content of all the parts will be copied into the body, with the part title displayed as a top-level sub-heading. </p>
  <% end %>
  </div>

  <%= form_for @resource, url: duplicate_edition_path(@resource, from: edition_class.to_s), method: "post" do |f| %>
    <%= f.label :to, "Create as new" %>
    <%= select_tag :to, options_for_select(format_conversion_select_options(@resource)), class: "form-control input-md-3 add-bottom-margin"%>
    <%= f.submit "Change format", class: "btn btn-default" %>
  <% end %>
<% end %>

app/views/shared/_edition_activity_fields.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <header class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-title"><%= title %></h3>
  </header>

  <%= form_builder.fields_for(inline ? "activity_#{activity}_attributes" : :activity) do |activity_fields| %>
    <div class="modal-body">
      <%= activity_fields.hidden_field :request_type, value: activity %>

      <% if activity == :send_fact_check %>
        <%= activity_fields.input :email_addresses, hint: 'You can enter multiple email addresses if you comma separate them as follows: <code>fact-checker-one@example.com, fact-checker-two@example.com</code>.'.html_safe %>

        <%= activity_fields.label :customised_message do %>
          Customised message<abbr title="required">*</abbr>
        <% end %>
        <textarea id="edition_activity_send_fact_check_attributes_customised_message"
                  name="edition[activity_send_fact_check_attributes][customised_message]"
                  class="form-control" cols="60" rows="14"><%= render :template => 'noisy_workflow/request_fact_check', formats: [:text] %></textarea>
      <% elsif activity == :resend_fact_check %>
        <% latest_status_action = form_builder.object.latest_status_action %>
        <% if latest_status_action&.is_fact_check_request? %>
          <%= activity_fields.label :email_addresses %>
          <p class="form-control-static"><%= latest_status_action.email_addresses %></p>

          <%= activity_fields.label :customised_message %>
          <div class="form-control-static"><%= format_and_auto_link_plain_text(latest_status_action.customised_message) %></div>
        <% end %>
      <% else %>
        <%= activity_fields.input :comment, :as => :text, :input_html => { :cols => 60, :rows => 6 } %>
      <% end %>

      <% if activity == :schedule_for_publishing %>
        <%= activity_fields.label :publish_at do %>
          Publish at <abbr title="required">*</abbr>
        <% end %>
        <div class="form-inline">
        <%= activity_fields.time_select :publish_at, {}, { class: 'date form-control' } %>
        &mdash;
        <%= activity_fields.date_select :publish_at, { order: [:day, :month, :year],
          default: Date.tomorrow, start_year: Date.today.year, end_year: Date.today.year.next },
          { class: 'date form-control' } %>
        </div>
      <% end %>
      <p class="help-block add-top-margin remove-bottom-margin">
        <i class="glyphicon glyphicon-exclamation-sign add-right-margin"></i>Changes you’ve made to this edition will also be saved.
      </p>
    </div>

    <footer class="modal-footer remove-top-margin">
      <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
      <%= (inline ? form_builder : activity_fields).submit(title, class: "btn btn-success") %>
    </footer>
    </div>
  <% end %>
</div>

app/views/shared/_edition_header.html.erb
<div class="page-title">
  <h1>
    <%= @resource.title %>
  </h1>
  <span class="lead">
    <span class="label label-default" title="Edition">#<%= @resource.version_number %></span>
    <span class="label label-default" title="Format"><%= @resource.format.underscore.humanize %></span>
    <span class="label label-info" title="Status"><%= @resource.status_text %></span>
  </span>
</div>
<% important_note = @resource.important_note %>
<%= render partial: 'shared/important_note', locals: {important_note: @resource.important_note} %>
<% if @resource.artefact.state == "archived" %>
  <div class="callout callout-danger add-bottom-margin">
    <h2 class="callout-title">You can’t edit this publication</h2>
    <div class="callout-body">
      This content has been unpublished and is no longer available on the website.<br />
      All editions have been archived.
      <% if @resource.retired_format? %>
        <br /><br />
        This content format has been retired.
      <% end %>
    </div>
  </div>
<% else %>
  <%= render 'shared/ready_or_review_or_fact_check' %>
<% end %>

app/views/shared/_edition_history.html.erb
  <div id="version<%= edition.version_number %>" class="panel panel-default">
    <div class="panel-heading">
      <a data-toggle="collapse" class="panel-title bold" href="#body<%= edition.version_number %>">
        <i class="glyphicon glyphicon-smaller-than-text glyphicon-chevron-down add-right-margin"></i>Edition <%= edition.version_number %>
      </a>
      <% if edition.version_number > 1 %>
        <%= link_to "Compare with edition #{edition.version_number - 1}",
                    diff_edition_path(edition),
                    class: "pull-right" %>
      <% end %>
    </div>

    <div class="panel-collapse collapse<% if edition_counter == 0 %> in<% end %>" id="body<%= edition.version_number %>">
      <ul class="panel-body list-unstyled remove-bottom-margin">
        <% edition_actions(edition).each do |action| %>
          <li class="action-<%= action_class(action) %> add-bottom-margin add-left-margin">
            <h4>
              <div class="add-label-margin normal">
                <time datetime="<%= action.created_at %>" class="text-muted add-label-margin">
                  <%= action.created_at.to_s(:govuk_date) %>
                </time>
              </div>
              <%= action.to_s %> by
              <% if action.requester %>
                <%= mail_to action.requester.email, action.requester.name %>
              <% else %>
                GOV.UK Bot
              <% end %>
            </h4>
            <% if action_note?(action) %>
              <% if action.comment_sanitized %>
                <div class="alert alert-error alert-block">
                  We found some potentially harmful content in this email which has been automatically removed. Please check the content of the message in case any text has been deleted as well.
                </div>
              <% end %>
              <blockquote class="<%= action_class(action) %>-note add-left-margin" data-module="toggle">
                <%= action_note(action) %>
              </blockquote>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

app/views/shared/_govspeak_help.html.erb
<section class="govspeak_help">

<p>For full examples see: <a href="https://govspeak-preview.herokuapp.com/guide" target="_blank" rel="noopener noreferrer external">the Govspeak Guide</a>.</p>

<h4>Headers</h4>
<p class="help-block">Note that the page already has a top heading from the article name.</p>
<pre>## Top level sub-heading
### Second level sub-heading</pre>

<h4>Text Styles</h4>
<pre>**This text will be bold**</pre>

<h4>Acronyms</h4>
<pre>*[HMRC]: Her Majesty's Revenue and Customs</pre>

<h4>Bulleted List</h4>
<pre>* item 1
* item 2
* item 3</pre>

<h4>Numbered List</h4>
<pre>1. item 1
2. item 2
3. item 3</pre>

<h4>List of steps</h4>
<pre>s1. First step
s2. Second step
s3. Final step</pre>

<h4>Tables</h4>
<pre>Fruit | Colour
-|-
apple | green
banana | yellow</pre>

<h4>Internal links</h4>
<p class="help-block">Use when linking to <code>http://www.gov.uk/</code>.</p>
<pre>[Income tax rates](/income-tax-rates)</pre>

<h4>External links</h4>
<pre>[link text](http://www.example.com)</pre>

<h4>Download link style</h4>
<pre>$D[link text](http://example.com)$D</pre>

<h4>Info boxes</h4>
<p class="help-block">These can contain other Govspeak items.</p>
<pre>^Info box^
%Warning or alert box%
@Highlighted information box@</pre>

</section>

app/views/shared/_history.html.erb
<div aria-hidden="true" class="modal" id="save-edition-note" role="dialog" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <header class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Add edition note</h3>
      </header>
      <%= semantic_form_for(:note, :url=> notes_path) do |f| %>
        <%= f.inputs do %>
          <%= hidden_field_tag :edition_id, resource.id %>
          <div class="modal-body">
            <%= f.input :comment, :label => 'Note', :as => :text, :required => false, :input_html => { :class=> 'form-control', :rows => 6, :cols => 120 } %>
            <p class="help-block">Summarise your changes, and briefly explain why if you didn't make any requested changes.</p>
          </div>
          <footer class="modal-footer remove-top-margin">
            <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
            <button class="btn btn-success" name="commit">Save edition note</button>
          </footer>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div aria-hidden="true" class="modal" id="update-important-note" role="dialog" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <header class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Update important note</h3>
      </header>
      <%= semantic_form_for(:note, :url=> notes_path) do |f| %>
        <%= f.inputs do %>
          <%= hidden_field_tag :edition_id, resource.id %>
          <%= hidden_field_tag "note[type]", Action::IMPORTANT_NOTE %>
          <div class="modal-body">
            <%= f.input :comment, :label => 'Important note', :as => :text, :input_html => { class: 'form-control', rows: 6, cols: 120, value: @resource.important_note ? @resource.important_note.comment : '' } %>
            <p class="help-block">Add important notes that anyone who works on this edition needs to see, eg “(Doesn’t) need fact check, don’t publish.” Each edition can have only one important note at a time.</p>
          </div>
          <footer class="modal-footer remove-top-margin">
            <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
            <%= f.submit :class=>"btn btn-success", :value=>'Save important note' %>
          </footer>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div id="edition-history" data-module="collapsible-group" data-expand-text="Expand all notes" data-collapse-text="Collapse all notes">
  <h3 class="remove-top-margin add-bottom-margin">History and notes</h3>

  <p class="add-bottom-margin if-no-js-hide">
    <a href="#" class="js-toggle-all">Expand all notes</a>
  </p>

  <div class="add-bottom-margin">
    <a href="#save-edition-note" class="btn btn-primary" data-toggle="modal"><i class="glyphicon glyphicon-comment add-right-margin"></i>Add edition note</a>
    <a href="#update-important-note" class="btn btn-default" data-toggle="modal"><i class="glyphicon glyphicon-exclamation-sign add-right-margin"></i>Update important note</a>
    <% if @resource.important_note %>
      <%= semantic_form_for(@resource.important_note, :url=> resolve_note_path, :html => { :class => "add-left-margin inline" }, :method => "put") do |f| %>
        <%= hidden_field_tag :edition_id, resource.id %>
        <%= f.submit :class=>"btn btn-default", :value => 'Delete important note' %>
      <% end %>
    <% end %>
  </div>

  <p class="add-bottom-margin">
    <% if resource.published? %>
      View this on the GOV.UK website <%= link_to "#{Plek.new.website_root}/#{resource.slug}", "#{Plek.new.website_root}/#{resource.slug}" %>.<br />
    <% elsif resource.safe_to_preview? %>
      Preview edition at <%= link_to preview_edition_path(resource), preview_edition_path(resource) %>.<br />
    <% else %>
      This edition can’t be previewed.<br />
    <% end %>
    Send fact check responses to <%= mail_to resource.fact_check_email_address %>
  </p>

  <div class="panel-group">
    <%= render collection: @resource.history, partial: '/shared/edition_history', as: 'edition' %>
  </div>
</div>

app/views/shared/_important_note.html.erb
<% unless important_note.blank? %>
<% with_history = important_note_has_history?(@resource) %>
<div class="callout callout-important-note add-bottom-margin" <% if with_history %>data-module="toggle"<% end %>>
  <div class="callout-body add-label-margin">
    <%= action_note(@resource.important_note) %>
  </div>
  <div class="callout-important-note-detail">
    Note <%= with_history ? 'updated' : 'created' %> <time datetime="<%= important_note.created_at %>"><%= important_note.created_at.to_date.to_s(:govuk_date_short) %></time>
    <% if important_note.requester.present? %> by <%= mail_to important_note.requester.email, important_note.requester.name, { class: 'link-inherit' }  %><% end %>
    <% if with_history %>
     <span class="if-no-js-hide"> – <a href="#" class="js-toggle link-muted">See history</a></span>
    <% end %>
  </div>

  <% if with_history %>
    <table class="table table-bordered table-striped add-top-margin remove-bottom-margin if-js-hide js-toggle-target">
      <thead>
        <tr class="table-header">
          <th class="important-notes-date-col">Date</th>
          <th class="important-notes-author-col">Author</th>
          <th class="important-notes-note-col">Note</th>
        </tr>
      </thead>
      <tbody>
        <% important_notes(@resource).each do |action| %>
          <tr>
            <td><%= action.created_at.to_date.to_s(:govuk_date) %></td>
            <td><%= mail_to action.requester.email, action.requester.name if action.requester %></td>
            <td><%= action_note(action) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>
<% end %>

app/views/shared/_ready.html.erb
<div class="alert alert-info">
  <p>Request this edition to be amended further.</p>
  <%= render 'shared/request_amendments' %>
</div>

app/views/shared/_ready_or_review_or_fact_check.html.erb
<% if @resource.in_review? %>
  <%= render '/shared/review' %>
<% elsif @resource.fact_check? %>
  <%= render '/shared/fact_check' %>
<% elsif @resource.fact_check_received? %>
  <%= render '/shared/fact_check_received' %>
<% elsif @resource.fact_check_skipped? %>
  <div class="alert alert-info">
    <p>Fact check was skipped for this edition.</p>
  </div>
  <%= render '/shared/ready' %>
<% elsif @resource.ready? %>
  <%= render '/shared/ready' %>
<% end %>

app/views/shared/_related_external_links.html.erb
<%= semantic_bootstrap_nested_form_for @artefact, url: update_related_external_links_edition_path(@resource) do |f| %>
  <div class='alert alert-info'>
    Once saved, related external links will be visible on the site the next time
    this publication is published.
  </div>

  <div class="related-external-links fieldset-section">
    <label class="section-label">Related external links</label><br />
    <%= f.fields_for :external_links do |link| %>
      <div class="nested-item">
        <div class="row relative">
          <div class="col-md-4">
            <%= link.label :title, "Title" %>
            <%= link.text_field :title, class: 'form-control' %>
          </div>
          <div class="col-md-5">
            <%= link.label :url, "URL" %>
            <%= link.text_field :url, class: 'form-control' %>
          </div>
          <%= link.link_to_remove "Remove this URL", :class => "remove-row remove-row-related" %>
        </div>
      </div>
    <% end %>

    <%= f.link_to_add "Add related external link", :external_links, :class => "btn btn-primary" %>
  </div>

  <br/>

  <%= f.submit 'Save links', class: "btn btn-success btn-large" %>
<% end %>

app/views/shared/_request_amendments.html.erb
<%= build_review_button(@resource, "request_amendments", "Needs more work").html_safe %>
<% if activity_forms_required? %>
  <%= edition_activities_forms(@resource, request_amendments: "Request amendments") %>
<% end %>

app/views/shared/_review.html.erb
<div class="alert alert-info">
  <% if @resource.latest_status_action(Action::REQUEST_REVIEW) %>
    <p><%= @resource.latest_status_action(Action::REQUEST_REVIEW).requester.name %> has requested this edition be reviewed.</p>
    <% if @resource.latest_status_action.requester == current_user %>
      <p>That&rsquo;s you! You'll get an email when it has been reviewed.</p>
      <% if skip_review? %>
        <p><%= build_review_button(@resource, "skip_review", "Skip review").html_safe %></p>
      <% end %>
    <% else %>
      <div class="workflow-buttons">
        <%= review_buttons(@resource)%>
      </div>
      <% if activity_forms_required? %>
        <%= review_forms(@resource)%>
      <% end %>
    <% end %>
  <% else %>
    <p>We're having trouble accessing the action data. This Edition has been requested to be reviewed.</p>
    <div class="workflow-buttons">
      <%= review_buttons(@resource)%>
    </div>
    <%= review_forms(@resource)%>
  <% end %>
</div>

app/views/shared/_workflow_buttons.html.erb
<div class="navbar navbar-inverse navbar-fixed-bottom text-center">
  <div class="navbar-inner">
    <div class="container-fluid">
      <div class="workflow-buttons navbar-btn">
        <% if @resource.locked_for_edits? %>
          <%= @resource.error_description %> can't be changed.
          <%= preview_button(@resource) %>
          <% if @resource.can_create_new_edition? %>
            <%= link_to 'Create new edition', duplicate_edition_path(@resource), class: 'btn btn-primary btn-large', method: :post %>
          <% end %>
          <% if @resource.in_progress_sibling.present? %>
            <%= link_to 'Edit existing newer edition', edition_path(@resource.in_progress_sibling), html_options: { "class" => "btn btn-primary btn-large"} %>
          <% end %>
          <%= progress_buttons(@resource, skip_disabled_buttons: true) %>
        <% else %>
          <%= f.submit 'Save', id: 'save-edition', class: 'btn btn-success btn-large js-save' %>
          <%= preview_button(@resource) %>
          <%= progress_buttons(@resource) %>
        <% end %>
      </div>
    </div><!--/.container-fluid -->
  </div><!--/.navbar-inner -->
</div><!--/.navbar -->

<div class="workflow-message js-status-message"></div>