config/routes.rb
Rails.application.routes.draw do
  get '/healthcheck' => 'healthcheck#check'

  resources :notes do
    put 'resolve', on: :member
  end

  get 'downtimes' => 'downtimes#index'

  resources :artefacts, only: [:new, :create, :update]

  resources :editions do
    member do
      get 'diff'
      get 'metadata'
      get 'history'
      get 'admin'
      get 'tagging', to: "editions#linking"
      get 'related_external_links', to: "editions#linking"
      get 'unpublish'
      post 'duplicate'
      post 'update_tagging'
      post 'process_unpublish'
      patch 'update_related_external_links'
      post 'progress'
      put 'review'
      post 'skip_fact_check', to: 'editions#progress',
        edition: {
          activity: {
            request_type: 'skip_fact_check',
            comment: "Fact check skipped by request."
            }
          }
    end

    resource :downtime, only: [:new, :create, :edit, :update, :destroy]
  end

  get 'reports' => 'reports#index', as: :reports
  get 'reports/progress' => 'reports#progress', as: :progress_report
  get 'reports/organisation-content' => 'reports#organisation_content', :as => :organisation_content_report
  get 'reports/edition-churn' => 'reports#edition_churn', as: "edition_churn_report"
  get 'reports/content_workflow' => 'reports#content_workflow', as: "content_workflow_report"

  get 'user_search' => 'user_search#index'

  resources :link_check_reports, only: %i(create show)

  post "/link-checker-api-callback" => "link_checker_api#callback", as: "link_checker_api_callback"
  get 'api/lookup-by-base-path', to: "publishing_api_proxy#lookup_by_base_path"

  resources :publications
  root to: 'root#index'

  # We used to nest all URLs under /admin so we now redirect that
  # in case people had bookmarks set up. Using a proc as otherwise the
  # path parameter gets escaped
  get "/admin(/*path)", to: redirect { |params, _req| "/#{params[:path]}" }

  mount GovukAdminTemplate::Engine, at: "/style-guide"
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include ActionView::Helpers::TagHelper

  before_action :authenticate_user!

  def index
  end

  def progress
    send_report "editorial_progress"
  end

  def organisation_content
    send_report "organisation_content"
  end

  def edition_churn
    send_report "edition_churn"
  end

  def content_workflow
    send_report "content_workflow"
  end

private

  def report_last_updated(report)
    mtime = mtime_for(report)
    if mtime
      content_tag :span, "Generated #{mtime.to_s(:govuk_date)}", class: "text-muted"
    else
      content_tag :span, "Report currently unavailable", class: "text-muted"
    end
  end
  helper_method :report_last_updated

  def mtime_for(report)
    File.stat(report_location(report)).mtime.in_time_zone(Time.zone)
  rescue Errno::ENOENT
    nil
  end

  def report_location(report)
    File.join(CsvReportGenerator.csv_path, "#{report}.csv")
  end

  def send_report(report)
    if File.exist?(report_location(report))
      send_file report_location(report),
        filename: "#{report}-#{mtime_for(report).strftime('%Y%m%d%H%M%S')}.csv",
        type: "text/csv",
        disposition: "attachment"
    else
      return head(:not_found)
    end
  end
end

app/views/reports/index.html.erb
<div class="page-header">
  <h1>CSV Reports</h1>
  <p>These reports are updated every hour.</p>
</div>

<p>
  <strong><%= link_to 'All documents for departmental distribution', organisation_content_report_path(format: :csv) %></strong><br />
  <%= report_last_updated("organisation_content")%>
</p>
<p>
  <strong><%= link_to 'Churn in non-archived editions', edition_churn_report_path(format: :csv) %></strong><br />
  <%= report_last_updated("edition_churn")%>
</p>
<p>
  <strong><%= link_to 'Progress on all non-archived editions', progress_report_path(format: :csv) %></strong><br />
  <%= report_last_updated("editorial_progress")%>
</p>
<p>
  <strong><%= link_to 'Content summary and workflow history', content_workflow_report_path(format: :csv) %></strong><br />
  <%= report_last_updated("content_workflow")%>
</p>

<% content_for :page_title, "Reports" %>